# Generated by Django 3.2 on 2021-04-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CATEGORY_1', 'Category #1'), ('CATEGORY_2', 'Category #2'), ('CATEGORY_3', 'Category #3'), ('CATEGORY_4', 'Category #4')], max_length=127)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
