# Generated by Django 3.2 on 2021-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('GBP', '£'), ('EUR', '€')], default='USD', max_length=3),
        ),
    ]
